name: Autonomous Mobile Robotics Laboratory (AMRL)
url: //amrl.cs.utexas.edu
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  projects:
    output: false